[[ -e ~/.bash_aliases ]] && . ~/.bash_aliases

# WSL stuff
explorer () {
	explorer.exe "$(wslpath -w "$1")"
}
wslcd() {
	cd "$(wslpath "$1")"
}

# If oh-my-zsh isn't installed:
# https://ianyepan.github.io/posts/moving-away-from-ohmyzsh/
# https://github.com/topfunky/zsh-simple/blob/master/.zshrc
[ -d ~/.oh-my-zsh ] || {
	autoload -U colors
	colors
	setopt prompt_subst
	HISTDUP=erase
	setopt appendhistory
	setopt sharehistory
	setopt incappendhistory
	setopt hist_ignore_all_dups
	setopt hist_save_no_dups
	setopt hist_ignore_dups
	setopt hist_find_no_dups
	setopt menucomplete
	PROMPT='%F{208}%n%f :: %F{226}%~%f %(?..[%?] )-> '
	autoload compinit
	compinit
}
