autoload -U colors
colors
setopt prompt_subst
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
setopt menucomplete
setopt autocd
autoload -Uz compinit
compinit
bindkey -e
autoload -U select-word-style && select-word-style bash
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
HISTDUP=erase
alias ls='ls --color'
alias l='ls --color'
alias gst='git status'
alias gd='git diff'
alias gco='git checkout'
alias gcl='git clone'
